---
- name: Installed Required Packages (1/5)
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: true

- name: Add Kubernetes apt repository (2/5)
  ansible.builtin.deb822_repository:
    name: kubernetes
    uris: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/"
    suites: "/"
    signed_by: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    enabled: true

- name: Installed Kubernetes Packages (3/5)
  ansible.builtin.apt:
    name: "{{ required_k8s_packages }}"
    state: present
    update_cache: true
  notify: Enable kubelet

- name: Hold Kubernetes packages at pinned version (4/5)
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ required_k8s_packages }}"

# Source - https://stackoverflow.com/a/75344866
# Posted by C-nan, modified by community and me. See post 'Timeline' for change history
# Retrieved 2026-09-23, License - CC BY-SA 4.0
- name: Install helm on master if not exists (5/5)
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v{{helm_version}}-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  args:
    creates: /usr/local/bin/helm
  when: k8s_install_helm
